image: debian:stretch
before_script:
  - ping code.axians.com -c 5
  - ping 159.100.69.153 -c 5
  - ping 1.1.1.1 -c 5
build:
  variables:
    CI_DEBUG_TRACE: "true"
  tags:
    - docker
  script:
    - apt update && apt install python3-pip -y
    - pip3 install platformio
    - sed -i 's/\/\/#define/#define/g' include/header.hpp
    - export LC_ALL=C.UTF-8
    - export LANG=C.UTF-8
    - platformio run

pages:
  variables:
    CI_DEBUG_TRACE: "true"
  tags:
    - docker
  script:
    - apt update && apt install doxygen -y
    - doxygen
    - mv doc/ public/
  artifacts:
    paths:
      - public
  only:
    - master
