image: debian:stretch
  tags:
    - "docker azure"
  script:
    - apt update && apt install python3-pip -y
    - pip3 install platformio
    - sed -i 's/\/\/#define/#define/g' include/header.hpp
    - export LC_ALL=C.UTF-8
    - export LANG=C.UTF-8
    - platformio run

pages:
  variables:
    CI_DEBUG_TRACE: "true"
  tags:
    - "docker azure"
  script:
    - apt update && apt install doxygen -y
    - doxygen
    - mv doc/ public/
  artifacts:
    paths:
      - public
  only:
    - master
